### ISSUE TITLE
Job descriptions separated by location

### ISSUE THREAD

**Issue by saracmcorreia** [fathomlondon/fathomlondon.com#335]
Careers page should separate job specs by location **or** the London page should only show London locations and a link to NYC careers page (and vice versa).

**Comment by AndrewJDick** [comment]
I'd propose that `/careers` links to a list of our office locations, and clicking a location link redirects to the careers listing for that region. 

That removes the assumption that the user is searching for a role based on their current location. 
It also enhances the overall user experience, since you can return to the careers hub rather than following a series of redirects on each careers page.

Example: https://www.rockstargames.com/careers/

Thoughts?

**Comment by saracmcorreia** [comment]
Makes sense. Also, we will in the future have everything on fath.om so it makes sense for it to be location abstract.

**Comment by saracmcorreia** [comment]
Maybe design can create a cool visual for each location? - London & New York (for now)

**Comment by petecorreia** [comment]
Good idea @AndrewJDick. Let's run this by design too. @danielvan

**Comment by malgorzataf** [comment]
Hey there, here's the updated design with City Toggle - any questions - just shout. You can find this in the main website file: https://www.dropbox.com/s/my0xh7oo3pxm9nh/Fathom_Website%20-%20final.sketch?dl=0 Included is rollover/click state and an illustration with a shorter list of roles

![careers - opt 3-1](https://user-images.githubusercontent.com/35142781/48126607-795f2980-e279-11e8-89aa-3c1acdc9ad83.png)

**Comment by andrewjdick** [comment]
@jjenzz looks like @malgorzataf has provided designs for the location toggle. 

Maybe one for you to pick up?
